name: Update strava activities
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 18 * * *'
jobs:
  update-strava-history:
    name: Update strava activities
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update strava activities
        run: |
          composer install --prefer-dist
          
          touch .env

          echo ENVIRONMENT=dev >> .env
          echo DISPLAY_ERROR_DETAILS=1 >> .env
          echo LOG_ERRORS=0 >> .env
          echo LOG_ERROR_DETAILS=0 >> .env
          echo STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }} >> .env
          echo STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }} >> .env
          echo STRAVA_REFRESH_TOKEN=${{ secrets.STRAVA_REFRESH_TOKEN }} >> .env
          
          bin/console app:strava:import-activity
          bin/console app:strava:build-files
      - name: Generate chart
        id: chart
        uses: robiningelbrecht/apache-echarts-action@v1.1.0
        with:
          width: 1000
          height: 300
          pass-options-as: file
          chart-option: 'build/chart.json'
      - name: Generate gauge
        id: gauge
        uses: robiningelbrecht/apache-echarts-action@v1.1.0
        with:
          width: 750
          height: 750
          pass-options-as: file
          chart-option: 'build/gauge.json'
      - name: Save generated charts
        run: |
          cat <<EOF > build/chart.svg
          ${{ steps.chart.outputs.svg }}
          EOF
          
          cat <<EOF > build/gauge.svg
          ${{ steps.gauge.outputs.svg }}
          EOF
      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          git diff --staged --quiet || git commit -m"Updated strava activities"
          git push
      - name: ntfy.sh
        uses: robiningelbrecht/ntfy-action@v1.0.0
        if: always()
        with:
            url: ${{ secrets.NTFY_URL }}
            topic: ${{ secrets.NTFY_TOPIC }}
            icon: 'https://github.githubassets.com/images/modules/profile/achievements/starstruck-default.png'
            job_status: ${{ job.status }}
          
